### ISSUE TITLE
Schema codegen failing with 'sh: gq: command not found\n'

### ISSUE THREAD

**Issue by ssbothwell** [OxfordAbstracts/purescript-graphql-client#36]
Let me start off by saying I write very little javascript and I don't really know what I'm doing. :shrug: 

I'm trying to run the example codegen script in the node repl and am getting the following error:
```
> require('./generate-purs-schema')()
Promise { <pending> }
> failed to get gql schema Error: Shell command exit with non zero code: 127
    at ChildProcess.<anonymous> (/home/solomon/Development/purescript/labtek/node_modules/exec-sh/lib/exec-sh.js:73:15)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:506:15)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:506:15)
    at Pipe.<anonymous> (net.js:675:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:126:14) {
  code: 127,
  stdout: '',
  stderr: 'sh: gq: command not found\n'
}
```

I am on nixos and may simply not have `gq` in scope in my shell, but I can't seem to figure out what `gq` is or where it is called. I don't see it referenced in `exec-sh.js`.

**Comment by ssbothwell** [comment]
I was missing the graphqurl tool.

**Comment by roryc89** [comment]
I have removed graphqurl as dependency so this should no longer be an issue
